title: Arthur Berberyan
logo: /assets/img/IMG_2480.JPG
description: I am a final-year physics graduate student at California State University, Northridge. If you would like to contact me, please message me at [arthurberberyan [at] gmail [dot] com](mailto:arthurberberyan@gmail.com?subject=[GitHub]%20Source%20Han%20Sans)).
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-minimal
