title: Arthur Berberyan
logo: /assets/img/IMG_2480.JPG
description: <em> I laugh when I hear that the fish in the water is thirsty. </em> -Kabir 
  title: false
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-minimal
