title: Arthur Berberyan
logo: /assets/img/IMG_2480.JPG
description: I am a final-year physics graduate student at California State University, Northridge. If you would like to contact me, please message me at arthurberberyan [at] gmail [dot] com.
If you are interested in viewing a more in-depth [CV](assets/img/berberyan_cv_2pg.pdf).
show_downloads: false
theme: jekyll-theme-minimal
