title: Arthur Berberyan
logo: /assets/img/IMG_2480.JPG
#description: I am currently a physics graduate student at California State University, Northridge. If you would like to contact me, please send me a message at arthurberberyan [at] gmail [dot] com.

If you are interested in viewing a more in-depth [CV](https://drive.google.com/file/d/1x-A8a9gdqChY7c9UFiRB-vglpUT1Sttb/view?usp=sharing).

[Astronomy Picture of the Day](https://apod.nasa.gov/apod/astropix.html)
show_downloads: false
theme: jekyll-theme-minimal
