title: Arthur Berberyan
logo: /assets/img/IMG_2480.JPG
description: I laugh when I hear that the fish in the water is thirsty. -Kabir
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-minimal
