title: Arthur Berberyan
logo: /assets/img/IMG_2480.JPG
description: I am currently a physics grad student at California State University, Northridge.
show_downloads: false
theme: jekyll-theme-minimal
