title: Arthur Berberyan
logo: /assets/img/IMG_2480.JPG
description: I am currently a physics grad student at California State University, Northridge. [Contact](arthurberberyan@gmail.com)
show_downloads: false
theme: jekyll-theme-minimal
